### ISSUE TITLE
how to fix it?

### ISSUE THREAD

**Issue by cn0xroot** [RangeNetworks/liba53#1]
when do make

g++ -O3 -Wall -fPIC -c a5.c bits.c gea.c kasumi.c utils.c ifc.cpp
Unable to exec g++.real: 没有那个文件或目录
make: **\* [liba53.so.1.0] 错误 2

**Comment by iedemam** [comment]
OS? Software branch? Error messages in English?

Sorry but without any actual information, there's not much we can do.

**Comment by cn0xroot** [comment]
OS：
Distributor ID: Ubuntu
Description:    Ubuntu 12.04 LTS
Release:    12.04
Codename:   precise

Error message:
g++ -O3 -Wall -fPIC -c a5.c bits.c gea.c kasumi.c utils.c ifc.cpp
Unable to exec g++.real:  No such file or directory
make: **\* [liba53.so.1.0] error 2

thank you :)

**Comment by iedemam** [comment]
First result on google: http://askubuntu.com/questions/254385/gcc-unable-to-exec-gcc-real-no-such-file-or-directory

`sudo apt-get install build-essential`

If that's already installed, try executing this to see if gcc even works:

`gcc --version`

If that doesn't work, some symbolic links are broken on your system I think. The answer to that is also in the link above.

Are you using the dev scripts?

**Comment by cn0xroot** [comment]
build-essential is the latest version

gcc --version print:
gcc.real (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

What aspect of the dev scripts?

**Comment by iedemam** [comment]
Are you using the dev scripts to set up your environment. They're now updated to work with Ubuntu 16.04: https://github.com/RangeNetworks/dev

**Comment by cn0xroot** [comment]
Might just try to change OS  
Thank you all the same -.-!

**Comment by iedemam** [comment]
Closing for now. Hopefully, that fixes it for you! If not, open up another one and I'll take a look.
